@startuml
title アセットバンドル管理

'アセットバンドル管理'
class AssetBundleManager {

}

interface IAssetBundleLoder {
  +LoadAssetBundle : AssetBundle
}

class WWWLoader {
  +LoadAssetBundle : AssetBundle
}

class WWWCacheOrDownloadLoader  {
  +LoadAssetBundle : AssetBundle
}

class LocalAssetBundleLoader {
  +LoadAssetBundle : AssetBundle
}

AssetBundleManager -down-> IAssetBundleLoder

WWWLoader .up.> IAssetBundleLoder
WWWCacheOrDownloadLoader .up.> IAssetBundleLoder
LocalAssetBundleLoader .up.> IAssetBundleLoder
@enduml
